[supervisord]
user=root
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:juiceshop]
directory=/juice-shop
command=/usr/local/bin/node /juice-shop/build/app.js
autostart=true
autorestart=true
stdout_logfile=/opt/stdout-juiceshop.log
stdout_logfile_maxbytes=3000000
stderr_logfile=/opt/stderr-juiceshop.log
stderr_logfile_maxbytes=3000000
environment=PORT="30000",NODE_ENV="production"

[program:zap]
directory=/zap/
command=/zap/zap-webswing.sh
autostart=true
autorestart=true
stdout_logfile=/opt/stdout-zap.log
stdout_logfile_maxbytes=3000000
stderr_logfile=/opt/stderr-zap.log
stderr_logfile_maxbytes=3000000
