[supervisord]
user=root
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:labg-app]
command=python3 /opt/labg/labg_app.py
autostart=true
autorestart=true
stdout_logfile=/opt/labg_app.log
stdout_logfile_maxbytes=3000000
stderr_logfile=/opt/labg_app.err
stderr_logfile_maxbytes=3000000
environment=ACTIVITY_ID="1",VICTIM_KEY="labg-default-victim-key"

[program:victim-worker]
command=python3 /opt/labg/victim_worker.py
autostart=true
autorestart=true
stdout_logfile=/opt/labg_victim.log
stdout_logfile_maxbytes=3000000
stderr_logfile=/opt/labg_victim.err
stderr_logfile_maxbytes=3000000
environment=ACTIVITY_ID="1",VICTIM_KEY="labg-default-victim-key"

[program:zap]
directory=/zap
command=/zap/zap-webswing.sh
autostart=true
autorestart=true
stdout_logfile=/opt/labg_zap.log
stdout_logfile_maxbytes=3000000
stderr_logfile=/opt/labg_zap.err
stderr_logfile_maxbytes=3000000
