[supervisord]
user=root
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:flask-app]
directory=/app
command=python3 app.py
autostart=true
autorestart=true
stdout_logfile=/opt/stdout-flask.log
stdout_logfile_maxbytes=3000000
stderr_logfile=/opt/stderr-flask.log
stderr_logfile_maxbytes=3000000

[program:zap]
directory=/zap/
command=bash zap-webswing.sh
autostart=true
autorestart=true
stdout_logfile=/opt/stdout-zap.log
stdout_logfile_maxbytes=3000000
stderr_logfile=/opt/stderr-zap.log
stderr_logfile_maxbytes=3000000

[program:victim-bot]
directory=/app
command=python3 victim_bot.py
autostart=true
autorestart=true
stdout_logfile=/opt/stdout-victim.log
stdout_logfile_maxbytes=3000000
stderr_logfile=/opt/stderr-victim.log
stderr_logfile_maxbytes=3000000
startretries=3
